### ISSUE TITLE
MM doesn't return the value of function tags.FlattenAndSet

### ISSUE THREAD

**Issue by neil-yechenwei** [VSChina/magic-modules#31]
$ bash scripts/gogetcookie.sh
$ make tools
$ GOGC=20 make lint
==> Checking source code against linters...
golangci-lint run ./...
azurerm/data_source_private_link_service.go:472:20: Error return value of `tags.FlattenAndSet` is not checked (errcheck)
	tags.FlattenAndSet(d, resp.Tags)
	                  ^
azurerm/resource_arm_private_link_service.go:575:20: Error return value of `tags.FlattenAndSet` is not checked (errcheck)
	tags.FlattenAndSet(d, resp.Tags)
	                  ^
WARN [runner/nolint] Found unknown linters in //nolint directives: deadcode unused 
GNUmakefile:40: recipe for target 'lint' failed
make: *** [lint] Error 1
The command "GOGC=20 make lint" exited with 2.
Done. Your build exited with 1.

**Comment by houkms** [comment]
@neil-yechenwei Can you attach your `api.yaml` file link? I didn't quite get the point.

**Comment by JunyiYi** [comment]
@houkms This is a newly introduced coding style by Hashicorp. Now we should use [`return tags.FlattenAndSet(d, resp.Tags)`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_virtual_network.go#L245) instead of the previous `return nil` in `Read` function.

To fix this we need to change a bunch of files and introduce some new helper functions. A good example would be [Ansible](https://github.com/VSChina/magic-modules/blob/azure_backend/templates/azure/ansible/resource.erb#L69). We can do the following things:

* Define similar `is_tags_defined?` and `is_tags?` helper functions in Terraform
* Exclude **root** `tags` flattening in [`build_sdk_object_to_property`](https://github.com/VSChina/magic-modules/blob/azure_backend/templates/azure/terraform/resource.erb#L182)
* Change [`return nil`](https://github.com/VSChina/magic-modules/blob/azure_backend/templates/azure/terraform/resource.erb#L184) to either `return tags.FlattenAndSet()` or `return nil` based on whether we have `tags` in **root** properties

**Comment by houkms** [comment]
Solved in PR #47

**Comment by houkms** [comment]
This issue is solved in #48
