### ISSUE TITLE
can not generate code when handling field: `syncStatus` (parameter required: false)

### ISSUE THREAD

**Issue by njuCZ** [VSChina/magic-modules#82]
using file: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2019-05-01-preview/appplatform.json

using mm to generate `appplatformapp/package-2019-05-01-preview/api.yml` terraform code, it throws error and can not generate codes.

there seems something wrong when handling field `syncStatus`

**Comment by magodo** [comment]
The problem here is that MM tries to find a sdk field named `syncStatus` among `CreateOrUpdate` request fields, and it failed to find one. From api.yaml, you can see it only exists in `Read` request.

The reason why MM will look for it in `CreateOrUpdate` is because `syncStatus` property is not `output` only, which means it will be used at `Create`/`Update` method in TF.

**Comment by magodo** [comment]
Duplicate of #88
